language:  java

env: 

  - JDK=8

dist: trusty
addons:
  apt: 
    packages:
      - oracle-java8-installer

matrix:
  allow_failures:
    - env: JDK=8-ea

script: ./.travis.sh

stages:
  - compile
  - test
  - deploy

#env:
#  - FOO=one
#  - FOO=two

jobs:
  include:
    - stage: compile
      script: ./compile
    - stage: deploy
      script: ./deploy

